### PR TITLE
Fix diffusion shadow

### LINKED ISSUE #3067: diffusion_test is non-deterministic
Ever since #3054 , the test suite sometimes gets errors when running this diffusion test:
http://groot.astro.sunysb.edu/Castro/test-suite/gfortran/2025-04-14/diffuse-2d.html

I am not sure if this is an OpenMP issue? or something else.  valgrind doesn't turn up anything.

### PR DESCRIPTION
**Pull request by zingale**
## PR summary

also fix a few other warnings.

not sure if this fixes #3067 

## PR checklist

- [ ] test suite needs to be run on this PR
- [ ] this PR will change answers in the test suite to more than roundoff level
- [ ] all newly-added functions have docstrings as per the coding conventions
- [ ] the `CHANGES` file has been updated, if appropriate
- [ ] if appropriate, this change is described in the docs

### CODE REVIEW

File: Exec/unit_tests/diffusion_test/Problem_Derive.cpp [hunk 1]
```diff
@@ -33,8 +32,8 @@ void deranalytic(const Box& bx, FArrayBox& derfab, int dcomp, int /*ncomp*/,
         r[2] = problo[2] + dx[2] * (static_cast<Real>(k) + 0.5_rt);
 #endif
         if (coord_type <= 1) {
-            for (int i; i < AMREX_SPACEDIM; ++i) {
-                r[i] -= problem::center[i];
+            for (int n; n < AMREX_SPACEDIM; ++n) {
```
Comment (zhichen3) [inline Exec/unit_tests/diffusion_test/Problem_Derive.cpp:35]: I should've initialized it, `n = 0`

Comment (zingale) [reply Exec/unit_tests/diffusion_test/Problem_Derive.cpp:35]: oh

Comment (zingale) [reply Exec/unit_tests/diffusion_test/Problem_Derive.cpp]: fixed

File: Exec/hydro_tests/RT/inputs_2d [hunk 2]
```diff
@@ -56,12 +56,17 @@ amr.refine.dengrad.max_level = 5
...
 
 # PLOTFILES
-amr.plot_file       = plt        # root name of plotfile
+amr.plot_file       = rho_contrast.3to1_plt # root name of plotfile, change if for each density contrast run!!
 amr.plot_int        = 100        # number of timesteps between plotfiles
 amr.derive_plot_vars = density xmom ymom zmom eden Temp pressure  # these variables appear in the plotfile
 
 # EOS
 eos.eos_assume_neutral = 1
+
```
Comment (zhichen3) [inline Exec/hydro_tests/RT/inputs_2d:68]: is this file supposed to be here?

Comment (zingale) [reply Exec/hydro_tests/RT/inputs_2d:68]: no, I'll revert that

**Comment by zingale** [comment]
there were some uninitialized loop counters, so this probably does explain #3067

**Review by zhichen3 — APPROVED** [review]
